{% set name = "napari-stress" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari_stress-{{ version }}.tar.gz
  sha256: 2a5da5afd34d6dfb72ba77e37f60f2bc67b660641a5c7103ef4855a077fbd6c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - dask-core
    - distributed
    - joblib
    - magicgui <=0.8.0  # Imported but not listed as a requirement
    - matplotlib-base   # Imported but not listed as a requirement
    - mpmath
    - napari
    - napari-matplotlib >=1.1.0
    - napari-process-points-and-surfaces >=0.4.0
    - napari-segment-blobs-and-things-with-membranes
    - napari-tools-menu >=0.1.15
    - numpy <1.24.0
    - pandas
    - pygeodesic
    - pyocclient
    - python >={{ python_min }}
    - pyshtools <=4.10.0
    - scikit-image
    - scipy
    - seaborn
    - tqdm
    - vedo >=2023.5.0
    - vispy

test:
  imports:
    - napari_stress
  commands:
    - pip list
    # - pip check  # Fails due to napari-assistant requiring jupyter, and jupytext
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-stress
  summary: Interactive surface analysis in napari for measuring mechanical stresses in biological tissues
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/campaslab/napari-stress

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jo-mueller
